name: Copy docs on release

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  copy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy docs
      run: rsync -av --exclude='previous' docs/ docs/previous/${{ env.GITHUB_REF }}
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Copy docs to previous on release ${{ env.GITHUB_REF }}"
    - name: Push changes
      run: |
        eval `ssh-agent -s`; echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null; git push origin HEAD:main
