name: Copy docs on release

on:
  release:
    types: [published]

jobs:
  copy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy docs
      run: rsync -av --exclude='previous' docs/ docs/previous/${{ env.GITHUB_REF }}
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Copy docs to previous on release ${{ env.GITHUB_REF }}"

    - name: Start SSH agent
      run: ssh-agent -s
      shell: bash

    - name: Set ssh-agent env
      run: echo "::set-env name=SSH_AUTH_SOCK::$SSH_AUTH_SOCK"
      shell: bash

    - name: Add ssh key
      run: ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
      env:
        SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

    - name: Push changes
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
        git push origin ${{ env.GITHUB_REF }}
